### ISSUE TITLE
Markdown editor in create page.

### ISSUE THREAD

**Issue by getogrand** [SaturDJang/warp#19]
Markdown editor has to have these functions.
- editing
- markdown syntax highlight
- Integration with preview function.

**Comment by mingrammer** [comment]
Is there syntax highlighting feature now?

**Comment by getogrand** [comment]
@mingrammer Nope.
We have to implement syntax highlight feature, but it's not the time.
We have to rewrite markdown editor for this feature.

**Comment by qkraudghgh** [comment]
We use ace editor
this issue closed
