### ISSUE TITLE
Add private field on Presentation model

### ISSUE THREAD

**Issue by kyunooh** [SaturDJang/warp#2]
It need to add field about that is private document or not.

**Comment by mingrammer** [comment]
Suggest : 

is_public = models.BooleanField(default=True)

**Comment by kyunooh** [comment]
Okay that is good!

**Comment by mingrammer** [comment]
Will you send a PR? @kyunooh

**Comment by kyunooh** [comment]
Nope :D, I think this is not hard to us. but It will be help to someone who haven't to try pull request. so I will not resolve this now. Is it okay?

**Comment by mingrammer** [comment]
Nice
