### ISSUE TITLE
Apply nice design without eyesore.

### ISSUE THREAD

**Issue by getogrand** [SaturDJang/warp#21]

**Comment by mingrammer** [comment]
What is nice design?

**Comment by getogrand** [comment]
@mingrammer Ah.. I don't know actually.. But we know that we should have a nice design, aren't we? 😄

**Comment by qkraudghgh** [comment]
- [x] Main page
- [ ] Detail Page
- [ ] Create Page & Edit Page 
- [x] ETC Page (like. sign up, sign out, login etc..)
- [x] Default Structure (Header, variables, Tone and Manner...)

If the feature has not been created yet, I will just make a rough layout.

**Comment by qkraudghgh** [comment]
I close this Issue and open new issue for Detail and Create Pages
