### ISSUE TITLE
Remove IDEA related files on repository and add those to .gitignore

### ISSUE THREAD

**Issue by getogrand** [SaturDJang/warp#26]

**Comment by kyunooh** [comment]
Yes I will try

**Comment by kyunooh** [comment]
It was completed. close issue.

**Comment by getogrand** [comment]
Still there are IDEA related files on repository.

**Comment by mingrammer** [comment]
@getogrand There seems no IDEA files. Can I close this?

**Comment by getogrand** [comment]
@mingrammer Sure! Thanks!!
