### ISSUE TITLE
How to convert markdown to html in realtime.

### ISSUE THREAD

**Issue by kyunooh** [SaturDJang/warp#3]
We should find some library about convert to html. and it should be easy to edit code for making slide.

or the other way is we make it. I think that is not that hard now.

ps. This issue is not about django feature. so It is not need to make by everybody.
If you wanted to implement this feature, you assign to yourselves. or ask to help to another one.

**Comment by mingrammer** [comment]
I found a js library https://github.com/evilstreak/markdown-js

How about using this? (I did not ever use it)

**Comment by getogrand** [comment]
We are studying Django which is a PYTHON Web framework, NOT JS one.
So I think we should use python markdown parser. ex) [python-markdown2](https://github.com/trentm/python-markdown2) (I've not ever use it too)
We can implement realtime thing and learn Django more, using python md parser and ajax.

**Comment by kyunooh** [comment]
Wow.... We need to talk about it. I think both of them are correct way.

**Comment by getogrand** [comment]
We've discussed about JavaScript vs Python for parser on our team slack.
In conclusion, we decided to use JavaScript for markdown parsing.

**Comment by mingrammer** [comment]
So, we should choose a markdown-parser js library. (like above library i found)

**Comment by getogrand** [comment]
1. [markdown-js](https://github.com/evilstreak/markdown-js)
   - Simple usage
   - 5108 stars
   - Code was stopped on 2015 May
2. [showdown](https://github.com/showdownjs/showdown)
   - You should initiate converter on your own hands(?)
   - 3902 stars
   - Last commited on Aug 20
   - Mid-active on 2016.
3. [marked](https://github.com/chjj/marked)
   - Not bad to my eyes.
   - 10535 stars
   - Last commited on 19 days ago
   - Not active on 2016.

**Comment by getogrand** [comment]
### Benchmark is shown on [marked README doc](https://github.com/chjj/marked#benchmarks)

$ node test --bench
marked completed in 3411ms.
marked (gfm) completed in 3727ms.
marked (pedantic) completed in 3201ms.
robotskirt completed in 808ms.
showdown (reuse converter) completed in 11954ms.
showdown (new converter) completed in 17774ms.
markdown-js completed in 17191ms.

**Comment by mingrammer** [comment]
marked +1

**Comment by kyunooh** [comment]
marked! LGTM :D
