### ISSUE TITLE
Add contributing rules

### ISSUE THREAD

**Issue by mingrammer** [SaturDJang/warp#5]
We seem to need contributing rules for maintaining this project well.

example : 
1. The commit message must be started uppercase letter (ex> Fix typo errors about ...)
2. The contributing related to 'documentation' can be merged when has one review at least.
3. The contributing related to  'source code' can be merged when has two reviews at least.
4. The contributing about specific issue must be on other branch not master (like 'issue-[number]' branch)
5. The contributing about bugs must be on other branch with name of some rules (ex> 'fix-[issue-number]')
6. and so on ...

So, I suggest that we have to discuess about this issue on saturday.

**Comment by mingrammer** [comment]
Are you agree with that rules?

**Comment by kyunooh** [comment]
Yes I think that is enough to us yet :D Thank you. Could you make contributing.rst?

**Comment by mingrammer** [comment]
Ok, I'll make it soon.
