### ISSUE TITLE
Redefine git branch strategy

### ISSUE THREAD

**Issue by qkraudghgh** [SaturDJang/warp#58]
I think there are three reasons for push branch. (exactly four)

1. Create new feature
2. Modified existing feature
  2-1. bugfix
  2-2. enhance
3. hot-fix - not issue based (ex. fix misprint)

In that context, we have two ways of naming a git branch, 
One is `issue-[number]` and the other is `fix-issue-[number]`.

Our strategy does not handle all cases.
I think,`issue-[number]` covered 1, 2-2 and `fix-issue-[number]` covered 2-1,
but number 3 is not covered by anything.

So I suggest create `hotfix/[fixed-summary]` branch

If you have any other comments, please let me know. 

Thanks

**Comment by getogrand** [comment]
I think there is no need to have `fix-issue-[number]`. 
The `issue-[number]` strategy covers `fix-issue-[number]`.

How about just use two strategies below?
1. `issue-[number]`
2. `hotfix/[fixed-summary]`

**Comment by qkraudghgh** [comment]
Sounds great. I agree
But how about talking on Saturday?

**Comment by getogrand** [comment]
Noproblema!

**Comment by mingrammer** [comment]
We could consider the `gitflow` too.

**Comment by getogrand** [comment]
https://news.ycombinator.com/item?id=9744059
> GitLab CEO here. I agree that GitFlow is needlessly complex and that there should be one main branch. The author advises to merge in feature branches by rebasing them on master. I think that it is harmful to rewrite history. You will lose cherry-picks, references in issues and testing results (CI) of those commits if you give them a new identifier.

I think master/develop strategy is a pain. We make new branch for requesting pull request. 
So there is no reason that we have to develop branch. 
Master is a branch for only production deploy? There is **tag**.
Let's see other's repositories. The super-heavy repo **Linux** does not use develop branch. They use just a master branch and branches for pull requests.
https://github.com/torvalds/linux
https://github.com/textmate/textmate

**Comment by qkraudghgh** [comment]
OK.

we use two branch naming strategy

1. [title_text]-[issueNumber] / covered 1, 2 / Issue [O], PR [O]
2. hotfix/[title_text] / covered 3 / Issue [X], PR [O]

WE DONT USE DIRECT PUSH TO MASTER BRANCH
