### ISSUE TITLE
Improve build speed of Docker.

### ISSUE THREAD

**Issue by getogrand** [SaturDJang/warp#74]
Currently, docker build is too slow. 
The `docker-compose up --build` takes 20min in my MBP machine.

See https://medium.com/playmoweb-android-ios-development/speed-up-your-builds-with-docker-cache-bfed14c051bf#.xgkcfjh7k

**Comment by qkraudghgh** [comment]
I think we solved this problem.
But we must have to re-setting to docker-file for Deploy(production) ENV
