### ISSUE TITLE
Add flake8 lint checking to travis

### ISSUE THREAD

**Issue by mingrammer** [SaturDJang/warp#86]
I want to add the flake8 (pep8 + pyflakes) linting checking to travis

How about you?

**Comment by maxtortime** [comment]
I have added pep8 checking to my project. I'll find about pyflakes and create pull request.

**Comment by maxtortime** [comment]
https://gist.github.com/MichaelCurrie/802ce28c993ff2dd632c
@mingrammer Do you want to apply this script?

**Comment by myungseokang** [comment]
I like this! :+1:
